version: '2'
services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "coolwang"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      #大小写不敏感
      --lower_case_table_names=1
      --max_allowed_packet=128M
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    mem_limit: 1g
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge