version: '2'
services:
  redis:
    image: redis:3.0.6
    container_name: redis
    restart: always
    #设置密码 coolwang
    command: redis-server --requirepass coolwang 
    ports:
      - 6379:6379
    volumes:
      # 持久化数据
      - ./data:/data
      - /etc/localtime:/etc/localtime
    mem_limit: 1g
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge